### ISSUE TITLE
Finish setup section in readme

### ISSUE THREAD

**Issue by RSid** [MassBailFund/MassBailFund#80]
@AlexRiina would you mind taking a look at what I've added to the readme & let me know if there was anything I've forgotten or mis-remembered? Thanks!

**Comment by AlexRiina** [comment]
I think that'll get a new user up and running. The issues I ran into initially were mostly around my mysql being stricter about table case and groupings and I've rewritten all of the lines that failed for me.

```
Run rake db:migrate.
Set environment variable MA_BAIL_USER_PASSWORD with your desired password for your local admin user. You may also wish to alter the username in seed.rb.
Run rake db:seed.
```

I think this might be equivalent to `rails db:reset` if MA_BAIL_USER_PASSWORD is set. Based on https://stackoverflow.com/a/10302357/3208419 I think db:migrate wont create the database, so that might have to be a different step.

For the ruby version, I think .ruby-version is supported by a few managers like rbenv, chruby, and rvm and mine has been automatically created as "2.5.1". We could also put something like `ruby "~> 2.5.0"` in the Gemfile for a similar effect I think. I think heroku defaults to 2.5.1, but I'm not sure.

**Comment by petedannemann** [comment]
Hey @RSid, this code base looks great and thanks for putting together some installation instructions. I'm working with PhillyBailFund and we wanted to take a look at your project, but I'm having a hard time getting the setup commands to run. I don't have much experience with Ruby so maybe I'm missing something obvious. I'm using a fresh install of ruby 2.4.2.

```bash
$ ruby -v
>>> ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

$ bundle install
>>> Lots of packages install and three or four warning messages.

$ rake db:migrate
>>> Lots of errors related to not having pg in my Gemfile (which doesn't make sense since this uses MySQL not PostGreSQL?)
```
_Add pg to Gemfile_

```bash
$ rake db:migrate
>>> == 20170507015636 ImportExistingSchema: migrating =============================
-- adapter_name()
   -> 0.0001s
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
 -- create_table("ATTACHMENTS", {:primary_key=>"ATTACHMENT_ID", :force=>:cascade, :options=>"ENGINE=MyISAM DEFAULT CHARSET=utf8", :id=>:integer})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::SyntaxError: ERROR:  syntax error at or near "ENGINE"
LINE 1: ..."FILENAME" character varying, "ATTACHMENT" bytea) ENGINE=MyI...
```
Maybe this is related to what @AlexRiina is saying above, where the database needs to be created first? I'd appreciate any advice on where to go from here, and thanks again for making your work publicly available so other bail funds can use  it!

**Comment by petedannemann** [comment]
Hey @RSid and @AlexRiina, I'm working with Philadelphia's Bail Fund and thanks for making this available for us to use. Setup was relatively straightforward with your instructions, minus some weird dependencies that I ran into most likely because I was using Ubuntu. @AlexRiina is right though, the user will need to create the database. I wasn't sure if there was a script for it so I just ran:

```bash
$ mysql -u root -p
>>> Enter your password: averysecurepassword

$ CREATE DATABASE mass_bail_fund_development;
>>> mass_bail_fund_development created successfully.
```

Thanks again and the site looks awesome!

**Comment by AlexRiina** [comment]
Thanks!

```
MA_BAIL_USER_PASSWORD=hi8there rails db:reset
```

creates the database and runs the migrations if you need to start from scratch. I'm using Ubuntu too and ran into some issues where my local mysql was more recent than the heroku mysql and ended up raising a lot of warnings that I resolved. Is that similar to what you encountered?

**Comment by petedannemann** [comment]
Awesome, I'll definitely do that next time. I didn't run into any MySQL issues but nokogiri, a dependency of rails, wouldn't install and I think I had to [end up running](https://stackoverflow.com/questions/30780988/error-installing-nokogiri-in-ubuntu-14-0-4-ruby-1-8-7):

```bash
$ sudo apt-get install libxml2-dev
$ sudo apt-get install libxslt-dev
```

After that ExecJS wouldn't install and that was [fixed by installing Node.js](https://stackoverflow.com/questions/6282307/execjs-and-could-not-find-a-javascript-runtime)
```
sudo apt-get install nodejs
```

**Comment by RSid** [comment]
Welcome Pete & thanks for the feedback both of you! I'll try doing setup on my linux machine at work and see what I run into - I'm usually doing MBF work on a Mac.

I'll also update the readme to use db:reset instead, note the node dependency, and specify the Ruby version in our gemfile.

**Comment by RSid** [comment]
Setup ran smoothly on Ubuntu with the new instructions, so I'm going to close out this ticket. Thanks!
